


linkedin:
  client-id: 86mi7uhgg05ymd
  client-secret: VOigSRMlMJRGVhGc
  redirect-uri: http://localhost:3000/auth/linkedin/callback
# Set the maximum file size allowed for uploads (in bytes)
security.jwt.token.secret-key: my-secret-key
spring:

  mail:
    host: smtp.gmail.com
    port: 587
    username: frostmilano42@gmail.com
    password: "tjjj phkb fgap pkbe"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:

    hikari:
      auto-commit: false
      maximum-pool-size: 20
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-test-query: SELECT 1

    platform: postgres
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: SupremeGod99
#    url: jdbc:postgresql://lionseyepostgres.postgres.database.azure.com:5432/postgres
#    username: teasleyw
#    password: Bulleit652
    initialization-mode: always


  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: create
logging:
  level:
    org:
      springframework:
        security: DEBUG
