#mail.host=smtp.gmail.com
#mail.port=587
#mail.username=FrostMilano42@gmail.com
#mail.password=nkqgrmqovgqtbyfh
#mail.properties.mail.smtp.auth=true
#mail.properties.mail.smtp.starttls.enable=true
security.jwt.token.secret-key: my-secret-key
spring:
  datasource:
    platform: postgres
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/portfolio
    username: postgres
    initialization-mode: always
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: create
logging:
  level:
    org:
      springframework:
        security: DEBUG